### ISSUE TITLE
【报错求助】启动报错ImportError: cannot import name 'field_validator' from 'pydantic’

### ISSUE THREAD

**Issue by Xian0Grem** [iyume/nonebot-plugin-nsfw#10]
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_nsfw\__init__.py", line 10, in <module>
    from nonebot_plugin_nsfw.config import PluginConfig, config
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_nsfw\config.py", line 6, in <module>
    from pydantic import BaseModel, NonNegativeInt, PositiveInt, field_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)

**Comment by Xian0Grem** [comment]
已经解决,参考   #7
