### ISSUE TITLE
【报错求助】Only instances of `keras.Layer` can be added to a Sequential model.

### ISSUE THREAD

**Issue by Xian0Grem** [iyume/nonebot-plugin-nsfw#11]
11-02 20:54:43 [ERROR] nonebot_plugin_nsfw | Only instances of `keras.Layer` can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x00000190CA71B7D0> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)
Traceback (most recent call last):
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
> File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_nsfw\loader.py", line 108, in _ctx_loader
    _loader()
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_nsfw\loader.py", line 87, in load_nsfw_model
    model = load_model(model_path)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\nonebot_plugin_nsfw\vendor_nsfw_model.py", line 70, in load_model
    model = tf.keras.models.load_model(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 133, in load_model_from_hdf5
    model = saving_utils.model_from_config(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\legacy\saving\serialization.py", line 495, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\models\sequential.py", line 359, in from_config
    model.add(layer)
  File "F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\keras\src\models\sequential.py", line 97, in add
    raise ValueError(
ValueError: Only instances of `keras.Layer` can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x00000190CA71B7D0> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)

11-02 20:54:43 [ERROR] nonebot_plugin_nsfw | Cannot load model, try to install using 'pip install nonebot-plugin-nsfw[nsfw-model]'

**Comment by iyume** [comment]
报错提示都贴出来了，用 `pip install nonebot-plugin-nsfw[nsfw-model]` 安装插件

**Comment by Xian0Grem** [comment]
> 报错提示都贴出来了，用 `pip install nonebot-plugin-nsfw[nsfw-model]` 安装插件

我尝试过了 不起作用


我漏复制了一段报错))))这段报错在上面的报错前面



WARNING:tensorflow:From F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

WARNING:tensorflow:From F:\NoneBot\nonebot_liyu\liyu\.venv\Lib\site-packages\tensorflow_hub\module_v2.py:126: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

2024-11-02 22:12:46.227616: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by iyume** [comment]
这个也不是报错啊，全是 warning，不能正常运行模型吗？

**Comment by iyume** [comment]
看起来像是依赖问题 https://github.com/tensorflow/tensorflow/issues/63085

你试试 `pip install nonebot-plugin-nsfw[nsfw-model] tensorflow==2.15.0`

**Comment by Xian0Grem** [comment]
> 看起来像是依赖问题 [tensorflow/tensorflow#63085](https://github.com/tensorflow/tensorflow/issues/63085)
> 
> 你试试 `pip install nonebot-plugin-nsfw[nsfw-model] tensorflow==2.15.0`

哦,跑起来了感谢❤️
